# Generated by Django 3.1.5 on 2021-03-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210325_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(),
        ),
    ]
