# Generated by Django 3.1.5 on 2021-03-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210325_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('TopWears', 'Top Wears'), ('FrontWears', 'Front Wears'), ('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('DailyNeeds', 'Daily needs'), ('Services', 'services'), ('Fashion', 'Fashion')], max_length=20),
        ),
    ]
