# Generated by Django 3.1.5 on 2021-03-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210326_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('TopWears', 'Top Wears'), ('FrontWears', 'Front Wears'), ('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('DailyNeeds', 'Daily needs'), ('  ', 'services'), ('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Laptop', 'Laptop')], max_length=20),
        ),
    ]
