# Generated by Django 3.1.5 on 2021-04-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210331_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_placed',
            name='user',
        ),
        migrations.AddField(
            model_name='order_placed',
            name='deliveryaddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
    ]
